################################################################################
# Authors: 
#
# Alfredo Sanchez-Tojar (alfredo.tojar@gmail.com): original code
#
# Pietro D'Amelio (pie.damelio@googlemail.com): revised & adjusted the code

# Script first created in Jan 2025 and sequentially revised until Jan 2026

################################################################################
# Description of script and Instructions
################################################################################

# This script is to re-analyse the meta-analytic data from:

# Assessing the Association Between Animal Color and Behavior: A Meta-Analysis 
# of Experimental Studies (https://doi.org/10.1002/ece3.70655)

# Data and Code from the original article obtained in Jan 2025 from:
# https://github.com/sruckman/meta-analysis/tree/master

# Note that this script is based on the original one oby Ruckman et al. on GitHub
# where we tried to keep original code lines where we could to avoid additional
# unncessary differences between both approaches


################################################################################
# Packages needed
################################################################################

# install.packages("pacman")
# load packages
pacman::p_load(metafor,
               orchaRd,
               ggplot2,
               dplyr,
               gridExtra,
               grid,
               ape,
               MCMCglmm,
               phytools,
               TreeTools,
               emmeans,
               bayestestR,
               ggstatsplot)

# cleaning up
rm(list = ls())

################################################################################
# Functions needed
################################################################################

# function to estimate typical sampling error variance
sigma2_v <- function(mod){
  sigma2_v <- sum(1 / mod$vi) * (mod$k - 1) /
    (sum(1 / mod$vi)^2 - sum((1 / mod$vi)^2))
  return(sigma2_v)
}

# # Sampling Variance for Zr # alternative function
# N.to.VZr <- function(N){
#   VZr <- 1/(N-3)
# }


################################################################################
# Data
################################################################################

# load the original dataset with the calculated effect sizes, provided by
# Ruckman et al. 2024: Dryad and GitHub
metadata <- read.csv("data/original/meta_complete_data2.csv", header=T)
# summary(metadata[metadata$Stat.Test=="mean","rho"])

# load the dataset generated by our own effect size code (001_)
metadata.new <- read.csv("data/new/meta_complete_data2_new.csv", header=T)
# summary(metadata.new[metadata.new$Stat.Test=="mean","yi"])

# comparing databases
nrow(metadata)
nrow(metadata.new)

# there is disagreement between our effect size dataset and theirs
setdiff(as.character(metadata$Species),
        as.character(metadata.new$Species))
setdiff(as.character(metadata.new$Species), # the name of one species is different
        as.character(metadata$Species))

length(unique(metadata$Species))
length(unique(metadata.new$Species)) # our dataset contains an extra species as a consequence


# for a reason we do not know, the following species did not make it to the 
# effect size dataset (i.e., metadata). It seems that the Haplochromis 
# omnicaeruleus was renamed as Haplochromis paludinosus, but we could not find
# a trace of that. We are implementing that change in our dataset for consistency 
metadata.new[metadata.new$Species=="Haplochromis omnicaeruleus",]
metadata[metadata$Species=="Haplochromis omnicaeruleus",]
sort(table(metadata$Species))
sort(table(metadata.new$Species))

setdiff(as.character(metadata$Authors),
        as.character(metadata.new$Authors))
setdiff(as.character(metadata.new$Authors),
        as.character(metadata$Authors))


# Let's rename the Haplochromis species
metadata.new$Species <- ifelse(metadata.new$Species=="Haplochromis omnicaeruleus",
                               "Haplochromis paludinosus",
                               metadata.new$Species)
nrow(metadata.new)
metadata.new.red <- metadata.new[,c("Study","yi","vi")] # for adding our own calculations
# nrow(metadata.new.red)
# nrow(metadata)

# # trying to understand the data better
# summary(metadata.new %>% group_by(Authors,Species) %>% summarise(n = n()))
# summary(metadata %>% group_by(Authors,Species) %>% summarise(n = n()))
# 
# summary(metadata.new[metadata.new$Species=="Haplochromis paludinosus",])
# summary(metadata[metadata$Species=="Haplochromis paludinosus",])
# 
# is.character(metadata.new.red$Study)
# is.character(metadata$Study)
# length(unique(metadata$Species))
# length(unique(metadata$Authors))

# we are adding our own estimates from metadata.new to the existing dataset
# provided by Ruckman et al. 2024
metadata.full <- merge(metadata,metadata.new.red,all.y=TRUE,by="Study")
# nrow(metadata.full)
# length(unique(metadata.full$Species))
# length(unique(metadata.full$Authors))

# all seems ok, back to the same name for the sake of code simplicity
metadata <- metadata.full

# New: Exploring Eu_Pheomelanin and Classification
summary(as.factor(metadata$Eu_Pheomelanin))

# NEW: Classification contains a formatting error: "melanocortin" vs "melanocortin "
# Unsure if this has any consequences down the line (updated: it does not)
summary(as.factor(metadata$Classification))

#Change Eu_Phae to represent all pigments: by the authors
metadata$Eu_Pheomelanin <- ifelse(metadata$Eu_Pheomelanin=="N/A", 
                                  metadata$Classification, 
                                  metadata$Eu_Pheomelanin)
#unique(metadata$Eu_Pheomelanin)
# NEW: looks like the melanocortin formatting error does not affect Eu_Pheomelanin

#we must change species to animal for the analysis to run, by the authors
metadata$animal <- metadata$Species

#remove pterinidine point (only one), by the authors
# NEW: which corresponds to the following data entry
# metadata[135,]
# The reason for excluding this entry according to the authors is because this
# is the only paper on pteridine-based coloration (Robertson and Rosenblum 2010)
#metadata <- metadata[c(1:134, 136:170),] #dangerous way of excluding data
table(metadata$Eu_Pheomelanin!="pteridine")
pteridine.species <- metadata[metadata$Eu_Pheomelanin=="pteridine","Species"]
metadata <- metadata[metadata$Eu_Pheomelanin!="pteridine",]
nrow(metadata)

# NEW: a potential issue with removing this entry is that the tree generated
# may contain the species that was seemingly removed from the dataset. 
# is the species removed by that entry removal still in the dataset?

metadata[metadata$animal%in%pteridine.species,]
metadata[metadata$animal==pteridine.species,]

# No, the species is no longer there, therefore, we may have to get rid of it 
# from the tree

# Change variables to be factors not characters
# New: code modified to avoid converting Publication.Year to a factor
names(metadata[,c(1:3,5:7,12:23,49)])
metadata[,c(1:3,5:7,12:23,49)] <- lapply(metadata[,c(1:3,5:7,12:23,49)], factor)


# # NEW: brief exploration of the final dataset
# summary(metadata)
# table(metadata$Species)
# length(unique(metadata$Species))
# as.data.frame(metadata %>% group_by(Species) %>% summarise(n = n()) %>% arrange(n))
# summary(metadata %>% group_by(Species) %>% summarise(n = n()))
# table(metadata$Study)
# length(unique(metadata$Authors))
# length(unique(metadata$Study))
# table(metadata$Authors)
# summary(metadata$Sample.Size)
# metadata[metadata$Sample.Size>200,]
# summary(metadata[metadata$Sample.Size>200,])
# hist(metadata$Sample.Size)
# summary(metadata$SE_Z)
# hist(metadata$SE_Z)
# table(metadata$Obs_vs_Exp)

# how many observational studies are in the data? Explore yi and vi differences
round(100*table(metadata$Obs_vs_Exp)/nrow(metadata),1)
metadata %>% group_by(Obs_vs_Exp) %>% summarise(yi = median(yi))
metadata %>% group_by(Obs_vs_Exp) %>% summarise(yi = median(vi))
# table(as.factor(metadata$Color1))
# table(as.factor(metadata$Color3))
# table(as.factor(metadata$Pattern))
# table(as.factor(metadata$Classification))
# table(as.factor(metadata$Aggression.Units))
# summary(metadata$Test.Statistic)
# table(as.factor(metadata$p.value))
#let's force p.value to be numeric, which it should be, despite some NA's and >
#reported
metadata$p.value.num <- as.numeric(metadata$p.value)
summary(metadata$p.value.num)

# var1 and var2 are empty variables, not sure why
table(as.factor(metadata$var1))
table(as.factor(metadata$var2))


################################################################################
# exploring outliers in mean vs sd: no action taken despite possible outliers

# are there any SD = 0? Yes, one
table(metadata$sd1==0)
table(metadata$sd2==0)

# are there any mean = 0? Yes 2 + 2
table(metadata$mean1==0)
table(metadata$mean1==0)

# # which studies
# metadata %>% filter(sd1==0)
# metadata %>% filter(sd2==0)
# metadata %>% filter(mean1==0)
# metadata %>% filter(mean2==0)
# 
# # looking at potential outliers
# plot(log(metadata$mean1),log(metadata$sd1))
# plot(log(metadata$mean2),log(metadata$sd2))
#
# metadata$log.mean1 <- log(metadata$mean1+0.1)
# metadata$log.sd1 <- log(metadata$sd1+0.1)
# metadata$log.mean2 <- log(metadata$mean2+0.1)
# metadata$log.sd2 <- log(metadata$sd2+0.1)
# 
# metadata.no.na <- metadata %>% filter(!(is.na(log.mean1)) & !(is.na(log.sd1)))
# 
# metadata.log.cor <- metadata %>% 
#   filter (Stat.Test=="mean" & 
#             mean1 > 0 &
#             mean2 > 0) %>%
#   mutate(log.mean1 = log(mean1),
#          log.sd1 = log(sd1),
#          log.mean2 = log(mean2),
#          log.sd2 = log(sd2))
# 
# 
# # exploring possible outliers
# ggscatterstats(
#   data = metadata.log.cor, ## data frame from which variables are taken
#   x = log.mean1, ## predictor/independent variable
#   y = log.sd1, ## dependent variable
#   xlab = "log(mean1)", ## label for the x-axis
#   ylab = "log(sd1)", ## label for the y-axis
#   type = "parametric",
#   label.var = Study, ## variable to use for labeling data points
#   label.expression = log.mean1 < -2.5, ## expression for deciding which points to label
#   xfill = "#CC79A7", ## fill for marginals on the x-axis
#   yfill = "#009E73", ## fill for marginals on the y-axis
# )
# 
# ggscatterstats(
#   data = metadata.log.cor, ## data frame from which variables are taken
#   x = log.mean2, ## predictor/independent variable
#   y = log.sd2, ## dependent variable
#   xlab = "log(mean2)", ## label for the x-axis
#   ylab = "log(sd2)", ## label for the y-axis
#   type = "parametric",
#   label.var = Study, ## variable to use for labeling data points
#   label.expression = log.mean1 < -2.5, ## expression for deciding which points to label
#   xfill = "#CC79A7", ## fill for marginals on the x-axis
#   yfill = "#009E73", ## fill for marginals on the y-axis
# )
# 
# metadata.log.cor %>% filter(log.mean1 < (-2.5))


################################################################################
# NEW: generating the variables needed for the following analyses
################################################################################

# NEW: first copying the animal variable to be able to fit the model with both
# phylogeny and species
metadata$species_phylo <- metadata$animal

# we need to model within-study/residual variation explicitly, we need a
# unit-level moderator to do so
metadata$EffectID <- 1:nrow(metadata)

# we need the sampling variances (rather than the sampling SE) to fit the model
# we can calculate them from the provided SE
metadata$VZr <- metadata$SE_Z^2

# # the alternative is to calculate them directly from the provided sample sizes
# metadata$VZr <- N.to.VZr(metadata$Sample.Size)
# 
# # as a check, let's compare our sampling SE (i.e. sqrt(VZr)) with the SE_Z 
# # provided in the dataset
# plot(sqrt(metadata$VZr),metadata$SE_Z) #it agrees, and therefore, passes this check
# cor.test(sqrt(metadata$VZr),metadata$SE_Z)


################################################################################
# Generating new phylogenetic information
################################################################################

# We are generating our own tree for this re-analysis. Note that we did that on
# the 02.03.2025, saved the data (see phylo info loaded below: load()), and here
# we are only adding the necessary changes to the species names. To repeat the 
# procees, uncomment the lines below, but keep in in mind that the phylo info
# may have changed since 02.03.2025, and additional changes may be required.

# # extracting taxonomic information: done on the 02.03.2025
# taxa.new <- rotl::tnrs_match_names(names = metadata$animal)
# taxa.new
# 
# # check approximate matches
# taxa.new[taxa.new$approximate_match==TRUE & !(is.na(taxa.new$approximate_match)),]
# 
# # check approximate matches
# taxa.new[taxa.new$is_synonym==TRUE & !(is.na(taxa.new$is_synonym)),]
# 
# # check number of matches
# taxa.new[taxa.new$number_matches>1 & !(is.na(taxa.new$number_matches)),]

# changing names in dataset to match the tree based on the three lines of code above
metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Phoenicoparrus minor",
                                    "Phoeniconaias minor",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Phoenicoparrus minor",
                                           "Phoeniconaias minor",
                                           as.character(metadata$species_phylo)))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Aastatotilapia burtoni",
                                    "Haplochromis burtoni",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Aastatotilapia burtoni",
                                           "Haplochromis burtoni",
                                           as.character(metadata$species_phylo)))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Cichlasoma citrinellum",
                                    "Amphilophus citrinellus",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Cichlasoma citrinellum",
                                           "Amphilophus citrinellus",
                                           as.character(metadata$species_phylo)))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Cichlasoma nigrofasciatum",
                                    "Amatitlania nigrofasciata",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Cichlasoma nigrofasciatum",
                                           "Amatitlania nigrofasciata",
                                           as.character(metadata$species_phylo)))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Gallus gallus domesticus",
                                    "Gallus gallus",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Gallus gallus domesticus",
                                           "Gallus gallus",
                                           as.character(metadata$species_phylo)))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Lacerta vivipara",
                                    "Zootoca vivipara",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Lacerta vivipara",
                                           "Zootoca vivipara",
                                           as.character(metadata$species_phylo)))

# # comparing the tree to our dataset
# intersect(as.character(taxa.new$unique_name),
#           as.character(metadata$animal))
# setdiff(as.character(metadata$animal),
#         as.character(taxa.new$unique_name)) # listed in our database but not in the tree
# setdiff(as.character(taxa.new$unique_name),
#         as.character(metadata$animal))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Astatotilapia burtoni",
                                    "Haplochromis burtoni",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Astatotilapia burtoni",
                                           "Haplochromis burtoni",
                                           as.character(metadata$species_phylo)))

# intersect(as.character(taxa.new$unique_name),
#           as.character(metadata$animal))
# setdiff(as.character(metadata$animal),
#         as.character(taxa.new$unique_name)) # listed in our database but not in the tree
# setdiff(as.character(taxa.new$unique_name),
#         as.character(metadata$animal))
# 
# # finally building tree
# tree.new <- rotl::tol_induced_subtree(ott_ids = taxa.new[["ott_id"]],
#                                   label_format = "name")
# 
# ape::is.binary(tree.new)
# 
# # here are the species included in the tree
# sort(tree.new$tip.label)
# 
# # removing the underscore "_" from the tree tip.label
# tree.new$tip.label <- gsub("_"," ", tree.new$tip.label)
# sort(tree.new$tip.label)
# 
# # comparing the tree to our dataset
# intersect(as.character(tree.new$tip.label),
#           as.character(metadata$species_phylo))
# setdiff(as.character(metadata$species_phylo),
#         as.character(tree.new$tip.label)) # listed in our database but not in the tree
# setdiff(as.character(tree.new$tip.label),
#         as.character(metadata$species_phylo)) # listed in the tree but not in our database
# 
# # time for the correlation matrix
# # compute branch lengths of tree
# phylo_branch.new <- compute.brlen(tree.new, method = "Grafen", power = 1)
# 
# # check tree is ultrametric
# is.ultrametric(phylo_branch.new) # TRUE
# 
# # matrix to be included in the models
# phylo_cor.new <- vcv(phylo_branch.new, cor = T)

# Saving the taxonomic data created on the 1st Jan 2025 to speed the
# process in the future and allow full reproducibility
# save(taxa.new, file = "new_taxonomy/taxa_Open_Tree_of_Life.RData")
# save(tree.new, file = "new_taxonomy/tree.Rdata")
# save(phylo_cor.new, file = "new_taxonomy/phylo_cor.Rdata")

load("new_taxonomy/taxa_Open_Tree_of_Life.RData") #resolved_names
load("new_taxonomy/tree.Rdata") #resolved_names
load("new_taxonomy/phylo_cor.Rdata") #resolved_names

# # We can plot the phylogenetic correlation matrix to observe how effect sizes
# # are distributed and species related
# ggcorrplot::ggcorrplot(phylo_cor.new, sig.level = 0.05, lab_size = 1,
#                        p.mat = NULL,insig = c("pch", "blank"),
#                        pch = 1, pch.col = "black", pch.cex = 1, tl.cex = 1.5) +
#   theme(axis.text.x = element_text(size = 7, margin = margin(-2, 0, 0, 0)),
#         axis.text.y = element_text(size = 7, margin = margin(0, -2, 0, 0)),
#         panel.grid.minor = element_line(size = 3)) +
#   geom_tile(fill = "white") +
#   geom_tile(height = 0.8, width = 0.8) +
#   scale_fill_gradient2(low = "#E69F00",mid = "white", high = "#56B4E9",
#                        midpoint = 0.5, breaks = c(0, 1),
#                        limit = c(0,1)) + labs(fill = "Correlation")


################################################################################
# Final variable needed for the analyses
################################################################################

# calculating sampling variance ourselves
metadata$V_Z <- (metadata$SE_Z)^2

# calculating sampling standard error ourselves
metadata$sei <- sqrt(metadata$VZr) # SE = sqrt(SV)

# calculating sampling variance ourselves
metadata$V_r <- (metadata$SE_r)^2


# To test small-study effects on r, we follow the general guidelines of Nakagawa
# et al. 2022, MEE. Instead of calculating effective sample size as: 
# (Nr + Nu)/(Nr * Nu), which we could only do for part of the dataset (e.g., not 
# for the correlations), we will simply use the the inverse of the sample size
# and its sqrt.
metadata$inv_esz <-  1/metadata$Sample.Size
metadata$sqrt_inv_esz  <-  with(metadata, sqrt(inv_esz))

# # if you wanted to test for decline effects, you could do the following:
# metadata$year.c <- scale(as.numeric(metadata$Publication.Year),scale=F)

# renaming factor levels for Stat.Test
metadata <- as.data.frame(
  metadata %>%
    mutate(Stat.Test = factor(Stat.Test, 
                              levels = c("r","mean","t","F","X2"))) %>%
    mutate(Stat.Test = recode(Stat.Test, r = "Pearson's r",
                              mean = "mean, SD, N",
                              t = "t value",
                              F = "F value",
                              X2 = "X2 value"))
)


################################################################################
# Analyses
################################################################################

# For reference, this is the intercept-only model fitted by Ruckman et al. 2024

# ################ RANDOM EFFECTS MODEL ####
# load("R Files/allRnd_Z.RDATA")
# 
# #priors:
# prior.ex <- list(G = list(G1 = list(V = 1, nu = 0.02, alpha.mu = 0.4, alpha.V = 0.5), 
#                           G2 = list(V = 1, nu = 0.02, alpha.mu = 0.4, alpha.V = 0.5), 
#                           G3 = list(V = 1, nu = 0.02, alpha.mu = 0.4, alpha.V = 0.5)), 
#                  R = list(V=1, nu=0.02))
# 
# #Run the model:
# allRnd.Z <- MCMCglmm(Fisher_Z ~ 1, random = ~animal + Authors + us(SE_Z):units,
#                      data=metadata, pedigree = tree, 
#                      nitt = 5000000, thin = 1000, burnin = 2500000, 
#                      prior = prior.ex)


################################################################################
# Re-analysis with provided data: Fisher’s Z transformed data before fixing code
################################################################################

# Not presented in the manuscript. This was originally done to understand what
# we considered odd patterns in the data, including the low heterogeneity and
# the potential issue with small-study effects. 

phylo.model.original.Zr <- rma.mv(yi = Fisher_Z,
                                  V = V_Z,
                                  mods = ~ 1,
                                  random = list(~ 1 | animal,
                                                ~ 1 | species_phylo,
                                                ~ 1 | Authors,
                                                ~ 1 | EffectID),
                                  method = "REML",
                                  R = list(species_phylo = phylo_cor.new),
                                  test = "t",
                                  data = metadata)


print(phylo.model.original.Zr,digits=3)
predict(phylo.model.original.Zr,digits=3)
predict(phylo.model.original.Zr,digits=3,trans=tanh) # as r instead Zr

##############
# Heterogeneity: calculating and understanding heterogeneity in the
# intercept-only model not account for phylogeny

# total sampling error
total_se_phylo.model.original.Zr <- sigma2_v(phylo.model.original.Zr)
round(total_se_phylo.model.original.Zr,3)

# total absolute variance
sigma2_phylo.model.original.Zr <- sum(phylo.model.original.Zr$sigma2)
round(sigma2_phylo.model.original.Zr,3)

# ratio of variance to sampling error
round(sigma2_phylo.model.original.Zr/total_se_phylo.model.original.Zr,1)

# I2 = variance-scaled heterogeneity
I2_phylo.model.original.Zr <- orchaRd::i2_ml(phylo.model.original.Zr)
round(I2_phylo.model.original.Zr,1)

# ratio of variance to sampling error: confirmation
round(I2_phylo.model.original.Zr[[1]]/(100-I2_phylo.model.original.Zr[[1]]),1)

# These heterogeneity metrics point at moderate to high levels of heterogeneity

# Plotting this results
results_phylo.model.original.Zr <- mod_results(phylo.model.original.Zr, 
                                               mod = "1", 
                                               at = NULL, group = "Authors")

figure_phylo.model.original.Zr <- orchaRd::orchard_plot(results_phylo.model.original.Zr, 
                                                        mod = "1", 
                                                        group = "Authors", 
                                                        xlab = "Effect size (original Zr)",
                                                        trunk.size = 1.5,
                                                        branch.size = 3,
                                                        twig.size = 1)

figure_phylo.model.original.Zr


################################################################################
# Publication bias tests

small_study_effects.phylo.model.original.Zr <- rma.mv(yi = Fisher_Z,
                                                      V = V_Z,
                                                      mods = ~ 1 + SE_Z,
                                                      random = list(~ 1 | animal,
                                                                    ~ 1 | species_phylo,
                                                                    ~ 1 | Authors,
                                                                    ~ 1 | EffectID),
                                                      method = "REML",
                                                      R = list(species_phylo = phylo_cor.new),
                                                      test = "t",
                                                      data = metadata)

summary(small_study_effects.phylo.model.original.Zr,digits=2)

figure_small_study_effects.phylo.model.original.Zr <- orchaRd::bubble_plot(small_study_effects.phylo.model.original.Zr, 
                                                                           mod = "SE_Z", 
                                                                           group = "Authors",
                                                                           ylab = "Effect size (original Zr)",
                                                                           xlab = "Sampling standard error (SE)",
                                                                           legend.pos = "bottom.right")
# The small-study effects plot shows that there is something really odd going on
# with the data.
figure_small_study_effects.phylo.model.original.Zr

# The amount of heterogeneity explained is:
round(r2_ml(small_study_effects.phylo.model.original.Zr)*100, 1)[1]


################################################################################
# PHYLOGENY: no Fisher's Z transformation: ROBUST (i.e., vcv)
################################################################################

# this is the main analysis presented in the manuscript. It uses our own 
# calculating of the effect sizes, as well as a VARIANCE-COVARIANCE MATRIX for
# modelling the sampling variances. Creating a var-covar matrix assuming a 0.5 
# correlation between effect sizes from the same study, which is a more robust
# and conservative way of modelling these hierarchal structures.

VCV_vi <- vcalc(vi = vi,
                cluster = Authors,
                obs = EffectID,
                data = metadata,
                rho = 0.5)  # assuming that the effect sizes within the same study are correlated with rho = 0.5

phylo.model.r.VCV <- rma.mv(yi = yi,
                            V = VCV_vi,
                            mods = ~ 1,
                            random = list(~ 1 | animal,
                                          ~ 1 | species_phylo,
                                          ~ 1 | Authors,
                                          ~ 1 | EffectID),
                            method = "REML",
                            R = list(species_phylo = phylo_cor.new),
                            test = "t",
                            data = metadata)


print(phylo.model.r.VCV,digits=3)
predict(phylo.model.r.VCV,digits=3)


##############
# Heterogeneity: calculating and understanding heterogeneity in the
# intercept-only model not account for phylogeny

# total sampling error
total_se_phylo.model.r.VCV <- sigma2_v(phylo.model.r.VCV)
round(total_se_phylo.model.r.VCV,3)

# total absolute variance
sigma2_phylo.model.r.VCV <- sum(phylo.model.r.VCV$sigma2)
round(sigma2_phylo.model.r.VCV,3)

# ratio of variance to sampling error
round(sigma2_phylo.model.r.VCV/total_se_phylo.model.r.VCV,1)

# I2 = variance-scaled heterogeneity
I2_phylo.model.r.VCV <- orchaRd::i2_ml(phylo.model.r.VCV)
round(I2_phylo.model.r.VCV,1)

# ratio of variance to sampling error: confirmation
round(I2_phylo.model.r.VCV[[1]]/(100-I2_phylo.model.r.VCV[[1]]),1)

# These heterogeneity metrics point at moderate to high levels of heterogeneity

# Plotting this results
results_phylo.model.r.VCV <- mod_results(phylo.model.r.VCV, 
                                         mod = "1", 
                                         at = NULL, group = "Authors")

figure_phylo.model.r.VCV <- orchaRd::orchard_plot(results_phylo.model.r.VCV, 
                                                  mod = "1", 
                                                  group = "Authors", 
                                                  xlab = "Effect size",
                                                  legend.pos = "none",
                                                  trunk.size = 1.5,
                                                  branch.size = 3,
                                                  twig.size = 1)

figure_phylo.model.r.VCV # Figure 1A


# ### exploring weights
# wi <- weights(phylo.model.r.VCV, type="rowsum")
# sum(wi * metadata$yi) / sum(wi)
# phylo.model.r.VCV.weight <- data.frame(k = c(table(metadata$Authors)),
#                                        weight = tapply(wi, metadata$Authors, sum))
# phylo.model.r.VCV.weight[order(phylo.model.r.VCV.weight$weight),]
# plot(phylo.model.r.VCV.weight$k,phylo.model.r.VCV.weight$weight)
# cor(phylo.model.r.VCV.weight$k,phylo.model.r.VCV.weight$weight)


################################################################################
# Publication bias tests

small_study_effects.phylo.model.r.VCV <- rma.mv(yi = yi,
                                                V = VCV_vi,
                                                mods = ~ 1 + sqrt_inv_esz,
                                                random = list(~ 1 | animal,
                                                              ~ 1 | species_phylo,
                                                              ~ 1 | Authors,
                                                              ~ 1 | EffectID),
                                                method = "REML",
                                                R = list(species_phylo = phylo_cor.new),
                                                test = "t",
                                                data = metadata)

summary(small_study_effects.phylo.model.r.VCV,digits=2)

# figure_small_study_effects.phylo.model.r.VCV <- orchaRd::bubble_plot(small_study_effects.phylo.model.r.VCV, 
#                                                                      mod = "sqrt_inv_esz", 
#                                                                      group = "Authors",
#                                                                      g = T,
#                                                                      ylab = "Effect size (r & rbis)",
#                                                                      xlab = "squared root of 1/effective N",
#                                                                      legend.pos = "bottom.right")
# 
# figure_small_study_effects.phylo.model.r.VCV # not presented

# The amount of heterogeneity explained is:
round(r2_ml(small_study_effects.phylo.model.r.VCV)*100, 1)[1]


################################################################################
# testing for differences between effect size origin

effect.size.origin.phylo.model.r.VCV <- rma.mv(yi = yi,
                                               V = VCV_vi,
                                               mods = ~ 1 + Stat.Test,
                                               random = list(~ 1 | animal,
                                                             ~ 1 | species_phylo,
                                                             ~ 1 | Authors,
                                                             ~ 1 | EffectID),
                                               method = "REML",
                                               R = list(species_phylo = phylo_cor.new),
                                               test = "t",
                                               data = metadata)

summary(effect.size.origin.phylo.model.r.VCV,digits=3)

# removing intercept to see each effect size separately (but see Figure 1C)
effect.size.origin.phylo.model.r.VCV.ni <- rma.mv(yi = yi,
                                               V = VCV_vi,
                                               mods = ~ -1 + Stat.Test,
                                               random = list(~ 1 | animal,
                                                             ~ 1 | species_phylo,
                                                             ~ 1 | Authors,
                                                             ~ 1 | EffectID),
                                               method = "REML",
                                               R = list(species_phylo = phylo_cor.new),
                                               test = "t",
                                               data = metadata)

summary(effect.size.origin.phylo.model.r.VCV.ni,digits=3)

fig_effect.size.origin.phylo.model.r.VCV <- orchaRd::orchard_plot(effect.size.origin.phylo.model.r.VCV, 
                                                                  mod = "Stat.Test", 
                                                                  group = "Authors", 
                                                                  xlab = "Effect size",
                                                                  trunk.size = 2,
                                                                  branch.size = 3,
                                                                  twig.size = 1)

fig_effect.size.origin.phylo.model.r.VCV # Figure 1C

# The amount of heterogeneity explained is: ~10%, which is substantial
round(r2_ml(effect.size.origin.phylo.model.r.VCV)*100, 1)[1]


# arranging these two plots to create half of Figure 1, i.e., panels A and C
# the remaining of this figure will be generated in script 006
grid.arrange(
  arrangeGrob(
    figure_phylo.model.r.VCV +
      theme(axis.title.x = element_blank(),
            axis.text.x  = element_text(size = 15),
            axis.text.y  = element_text(size = 15)) +
      annotate(
        geom = "text",
        x = 1.5, y = -0.75,
        label = paste0(
          "italic(I)^{2} == ",
          round(I2_phylo.model.r.VCV[[1]], 1),
          " *\"%\""
        ),
        parse = TRUE, size = 5.5
      ),
    top = textGrob("A)", x = unit(0, "npc"),
                   y = unit(1, "npc"),
                   just = c("left", "top"),
                   gp = gpar(fontsize = 14, fontface = "bold"))
  ),
  arrangeGrob(
    fig_effect.size.origin.phylo.model.r.VCV +
      theme(axis.title.x = element_text(size = 18, face = "bold"),
            axis.text.x  = element_text(size = 15),
            axis.text.y  = element_text(size = 15)) +
      annotate(
        geom = "text",
        x = 5.25, y = -0.75,
        label = paste0(
          "italic(R)[marginal]^{2} == ",
          round(r2_ml(effect.size.origin.phylo.model.r.VCV)*100, 1)[1],
          " *\"%\""
        ),
        parse = TRUE, size = 5.5
      ),
    top = textGrob("C)", x = unit(0, "npc"),
                   y = unit(1, "npc"),
                   just = c("left", "top"),
                   gp = gpar(fontsize = 14, fontface = "bold"))
  ),
  ncol = 1
)
