################################################################################
# Authors: 
#
# Alfredo Sanchez-Tojar (alfredo.tojar@gmail.com): original code
#
# Pietro D'Amelio (pie.damelio@googlemail.com): revised & adjusted the code

# Script first created in Jan 2025 and sequentially revised until Jan 2026

################################################################################
# Description of script and Instructions
################################################################################

# This script is to re-analyse the meta-analytic data from:

# Assessing the Association Between Animal Color and Behavior: A Meta-Analysis 
# of Experimental Studies (https://doi.org/10.1002/ece3.70655)

# Data and Code from the original article obtained in Jan 2025 from:
# https://github.com/sruckman/meta-analysis/tree/master

# This script uses the database after having validated data extraction for 11
# studies (15% of original database). Bear in mind that the results will be 
# contentious on the other 85% of articles being neutrally extracted.

################################################################################
# Packages needed
################################################################################

# install.packages("pacman")
# load packages
pacman::p_load(metafor,
               orchaRd,
               ggplot2,
               dplyr,
               gridExtra,
               grid,
               ape,
               MCMCglmm,
               phytools,
               TreeTools,
               emmeans,
               bayestestR,
               ggstatsplot)

# cleaning up
rm(list = ls())

################################################################################
# Functions needed
################################################################################

# function to estimate typical sampling error variance
sigma2_v <- function(mod){
  sigma2_v <- sum(1 / mod$vi) * (mod$k - 1) /
    (sum(1 / mod$vi)^2 - sum((1 / mod$vi)^2))
  return(sigma2_v)
}

# # Sampling Variance for Zr # alternative function
# N.to.VZr <- function(N){
#   VZr <- 1/(N-3)
# }


################################################################################
# Data
################################################################################

# import the dataset generated by our own effect size code
metadata.new.updated <- read.csv("data/new/meta_complete_data2_new_and_updated.csv", header=T)

# comparing databases
nrow(metadata.new.updated) #sample size after the reextraction of 15% of the dataset, and exclusion when necessary


# for a reason we don't fully understand, the following species did not make it 
# to the effect size dataset (i.e., metadata). It seems that the Haplochromis 
# omnicaeruleus was renamed as Haplochromis paludinosus, but we could not find
# a trace of that. We are implementing that change for our dataset
metadata.new.updated[metadata.new.updated$Species=="Haplochromis omnicaeruleus",]
sort(table(metadata.new.updated$Species))

# Let's rename the Haplochromis species
metadata.new.updated$Species <- ifelse(metadata.new.updated$Species=="Haplochromis omnicaeruleus",
                                       "Haplochromis paludinosus",
                                       metadata.new.updated$Species)
# nrow(metadata.new.updated)

# # trying to understand the data better
# summary(metadata.new.updated %>% group_by(Authors,Species) %>% summarise(n = n()))

# all seems ok, back to the same name for the sake of code simplicity
metadata <- metadata.new.updated

#removing first three unncessary columns
metadata <- metadata %>% select(-X.1,-X,-X.2)

#Change Eu_Phae to represent all pigments: by the authors
metadata$Eu_Pheomelanin <- ifelse(metadata$Eu_Pheomelanin=="N/A", 
                                  metadata$Classification, 
                                  metadata$Eu_Pheomelanin)
#unique(metadata$Eu_Pheomelanin)

# we must change species to animal for the analysis to run, by the authors
metadata$animal <- metadata$Species

# Change variables to be factors not characters
names(metadata[,c(1,3:14,16:23,25,43)])
metadata[,c(1,3:14,16:23,25,43)] <- lapply(metadata[,c(1,3:14,16:23,25,43)], factor)


# # NEW: brief exploration of the final dataset
# summary(metadata)
# table(metadata$Species)
# length(unique(metadata$Species))
# as.data.frame(metadata %>% group_by(Species) %>% summarise(n = n()) %>% arrange(n))
# summary(metadata %>% group_by(Species) %>% summarise(n = n()))
# table(metadata$Study)
# length(unique(metadata$Authors))
# length(unique(metadata$Study))
# table(metadata$Authors)
# summary(metadata$Sample.Size)
# metadata[metadata$Sample.Size>200,]
# summary(metadata[metadata$Sample.Size>200,])
# hist(metadata$Sample.Size)
# summary(metadata$Test.Statistic)


################################################################################
# NEW: generating the variables needed for the following analyses
################################################################################

# NEW: first copying the animal variable to be able to fit the model with both
# phylogeny and species
metadata$species_phylo <- metadata$animal

# we need to model within-study/residual variation explicitly, we need a
# unit-level moderator to do so
metadata$EffectID <- 1:nrow(metadata)


################################################################################
# Generating new phylogenetic information
################################################################################

# we are generating our own tree: which is the same as used in script 005. Here
# is the comment present in script 005, which applies here too:

# We are generating our own tree for this re-analysis. Note that we did that on
# the 02.03.2025, saved the data (see phylo info loaded below: load()), and here
# we are only adding the necessary changes to the species names. To repeat the 
# procees, uncomment the lines below, but keep in in mind that the phylo info
# may have changed since 02.03.2025, and additional changes may be required.

# # extracting taxonomic information: done on the 02.03.2025
# taxa.new <- rotl::tnrs_match_names(names = metadata$animal)
# taxa.new
# 
# # check approximate matches
# taxa.new[taxa.new$approximate_match==TRUE & !(is.na(taxa.new$approximate_match)),]
# 
# # check approximate matches
# taxa.new[taxa.new$is_synonym==TRUE & !(is.na(taxa.new$is_synonym)),]
# 
# # check number of matches
# taxa.new[taxa.new$number_matches>1 & !(is.na(taxa.new$number_matches)),]

# changing names in dataset to match the tree based on the three lines of code above
metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Phoenicoparrus minor",
                                    "Phoeniconaias minor",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Phoenicoparrus minor",
                                           "Phoeniconaias minor",
                                           as.character(metadata$species_phylo)))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Aastatotilapia burtoni",
                                    "Haplochromis burtoni",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Aastatotilapia burtoni",
                                           "Haplochromis burtoni",
                                           as.character(metadata$species_phylo)))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Cichlasoma citrinellum",
                                    "Amphilophus citrinellus",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Cichlasoma citrinellum",
                                           "Amphilophus citrinellus",
                                           as.character(metadata$species_phylo)))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Cichlasoma nigrofasciatum",
                                    "Amatitlania nigrofasciata",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Cichlasoma nigrofasciatum",
                                           "Amatitlania nigrofasciata",
                                           as.character(metadata$species_phylo)))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Gallus gallus domesticus",
                                    "Gallus gallus",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Gallus gallus domesticus",
                                           "Gallus gallus",
                                           as.character(metadata$species_phylo)))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Lacerta vivipara",
                                    "Zootoca vivipara",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Lacerta vivipara",
                                           "Zootoca vivipara",
                                           as.character(metadata$species_phylo)))

# # comparing the tree to our dataset
# intersect(as.character(taxa.new$unique_name),
#           as.character(metadata$animal))
# setdiff(as.character(metadata$animal),
#         as.character(taxa.new$unique_name)) # listed in our database but not in the tree
# setdiff(as.character(taxa.new$unique_name),
#         as.character(metadata$animal))

metadata$animal <- as.factor(ifelse(as.character(metadata$animal)=="Astatotilapia burtoni",
                                    "Haplochromis burtoni",
                                    as.character(metadata$animal)))

metadata$species_phylo <- as.factor(ifelse(as.character(metadata$species_phylo)=="Astatotilapia burtoni",
                                           "Haplochromis burtoni",
                                           as.character(metadata$species_phylo)))

# intersect(as.character(taxa.new$unique_name),
#           as.character(metadata$animal))
# setdiff(as.character(metadata$animal),
#         as.character(taxa.new$unique_name)) # listed in our database but not in the tree
# setdiff(as.character(taxa.new$unique_name),
#         as.character(metadata$animal))
# 
# # finally building tree
# tree.new <- rotl::tol_induced_subtree(ott_ids = taxa.new[["ott_id"]],
#                                   label_format = "name")
# 
# ape::is.binary(tree.new)
# 
# # here are the species included in the tree
# sort(tree.new$tip.label)
# 
# # removing the underscore "_" from the tree tip.label
# tree.new$tip.label <- gsub("_"," ", tree.new$tip.label)
# sort(tree.new$tip.label)
# 
# # comparing the tree to our dataset
# intersect(as.character(tree.new$tip.label),
#           as.character(metadata$species_phylo))
# setdiff(as.character(metadata$species_phylo),
#         as.character(tree.new$tip.label)) # listed in our database but not in the tree
# setdiff(as.character(tree.new$tip.label),
#         as.character(metadata$species_phylo)) # listed in the tree but not in our database
# 
# # time for the correlation matrix
# # compute branch lengths of tree
# phylo_branch.new <- compute.brlen(tree.new, method = "Grafen", power = 1)
# 
# # check tree is ultrametric
# is.ultrametric(phylo_branch.new) # TRUE
# 
# # matrix to be included in the models
# phylo_cor.new <- vcv(phylo_branch.new, cor = T)

# Saving the taxonomic data created on the 1st Jan 2025 to speed the
# process in the future and allow full reproducibility
# save(taxa.new, file = "new_taxonomy/taxa_Open_Tree_of_Life.RData")
# save(tree.new, file = "new_taxonomy/tree.Rdata")
# save(phylo_cor.new, file = "new_taxonomy/phylo_cor.Rdata")

load("new_taxonomy/taxa_Open_Tree_of_Life.RData") #resolved_names
load("new_taxonomy/tree.Rdata") #resolved_names
load("new_taxonomy/phylo_cor.Rdata") #resolved_names

# # We can plot the phylogenetic correlation matrix to observe how effect sizes
# # are distributed and species related
# ggcorrplot::ggcorrplot(phylo_cor.new, sig.level = 0.05, lab_size = 1,
#                        p.mat = NULL,insig = c("pch", "blank"),
#                        pch = 1, pch.col = "black", pch.cex = 1, tl.cex = 1.5) +
#   theme(axis.text.x = element_text(size = 7, margin = margin(-2, 0, 0, 0)),
#         axis.text.y = element_text(size = 7, margin = margin(0, -2, 0, 0)),
#         panel.grid.minor = element_line(size = 3)) +
#   geom_tile(fill = "white") +
#   geom_tile(height = 0.8, width = 0.8) +
#   scale_fill_gradient2(low = "#E69F00",mid = "white", high = "#56B4E9",
#                        midpoint = 0.5, breaks = c(0, 1),
#                        limit = c(0,1)) + labs(fill = "Correlation")


################################################################################
# Final variable needed for the analyses
################################################################################

# To test small-study effects on r, we follow the general guidelines of Nakagawa
# et al. 2022, MEE. Instead of calculating effective sample size as: 
# (Nr + Nu)/(Nr * Nu), which we could only do for part of the dataset (e.g. not 
# for the correlations), we will simply use the the inverse of the sample size
# and its sqrt.
metadata$inv_esz <-  1/metadata$Sample.Size
metadata$sqrt_inv_esz  <-  with(metadata, sqrt(inv_esz))

# renaming factor levels for Stat.Test
metadata <- as.data.frame(
  metadata %>%
    mutate(Stat.Test = factor(Stat.Test, 
                              levels = c("r","mean","t","F","X2"))) %>%
    mutate(Stat.Test = recode(Stat.Test, r = "Pearson's r",
                              mean = "mean, SD, N",
                              t = "t value",
                              F = "F value",
                              X2 = "X2 value"))
)

################################################################################
# Analyses
################################################################################

################################################################################
# PHYLOGENY: no Fisher's Z: ROBUST (i.e., vcv)
################################################################################

# this is the main analysis presented in the manuscript. It uses our own 
# calculating of the effect sizes, as well as:

#### CORRECTIONS OF DATA AND ADDITIONAL DATA FOUND TO BE MISSING DURING OUR
# SUBSET OF REEXTRACTIONS (15% of the studies, see script 004)

# and is in script 05: VARIANCE-COVARIANCE MATRIX for
# modelling the sampling variances. Creating a var-covar matrix assuming a 0.5 
# correlation between effect sizes from the same study, which is a more robust
# and conservative way of modelling these hierarchical structures.

VCV_vi <- vcalc(vi = vi,
                cluster = Authors,
                obs = EffectID,
                data = metadata,
                rho = 0.5)  # assuming that the effect sizes within the same study are correlated with rho = 0.5

phylo.model.r.VCV <- rma.mv(yi = yi,
                            V = VCV_vi,
                            mods = ~ 1,
                            random = list(~ 1 | animal,
                                          ~ 1 | species_phylo,
                                          ~ 1 | Authors,
                                          ~ 1 | EffectID),
                            method = "REML",
                            R = list(species_phylo = phylo_cor.new),
                            test = "t",
                            data = metadata)


print(phylo.model.r.VCV,digits=3)
predict(phylo.model.r.VCV,digits=3)


##############
# Heterogeneity: calculating and understanding heterogeneity in the
# intercept-only model not account for phylogeny

# total sampling error
total_se_phylo.model.r.VCV <- sigma2_v(phylo.model.r.VCV)
round(total_se_phylo.model.r.VCV,3)

# total absolute variance
sigma2_phylo.model.r.VCV <- sum(phylo.model.r.VCV$sigma2)
round(sigma2_phylo.model.r.VCV,3)

# ratio of variance to sampling error
round(sigma2_phylo.model.r.VCV/total_se_phylo.model.r.VCV,1)

# I2 = variance-scaled heterogeneity
I2_phylo.model.r.VCV <- orchaRd::i2_ml(phylo.model.r.VCV)
round(I2_phylo.model.r.VCV,2)

# ratio of variance to sampling error: confirmation
round(I2_phylo.model.r.VCV[[1]]/(100-I2_phylo.model.r.VCV[[1]]),1)

# These heterogeneity metrics point at moderate to high levels of heterogeneity

# Plotting this results
results_phylo.model.r.VCV <- mod_results(phylo.model.r.VCV, 
                                         mod = "1", 
                                         at = NULL, group = "Authors")

figure_phylo.model.r.VCV <- orchaRd::orchard_plot(results_phylo.model.r.VCV, 
                                                  mod = "1", 
                                                  group = "Authors", 
                                                  xlab = "Effect size",
                                                  legend.pos = "none",
                                                  trunk.size = 1.5,
                                                  branch.size = 3,
                                                  twig.size = 1)

figure_phylo.model.r.VCV # Figure 1B


# ### exploring weights
# wi <- weights(phylo.model.r.VCV, type="rowsum")
# sum(wi * metadata$yi) / sum(wi)
# phylo.model.r.VCV.weight <- data.frame(k = c(table(metadata$Authors)),
#                                        weight = tapply(wi, metadata$Authors, sum))
# phylo.model.r.VCV.weight[order(phylo.model.r.VCV.weight$weight),]
# plot(phylo.model.r.VCV.weight$k,phylo.model.r.VCV.weight$weight)
# cor(phylo.model.r.VCV.weight$k,phylo.model.r.VCV.weight$weight)


################################################################################
# Publication bias tests

small_study_effects.phylo.model.r.VCV <- rma.mv(yi = yi,
                                                V = VCV_vi,
                                                mods = ~ 1 + sqrt_inv_esz,
                                                random = list(~ 1 | animal,
                                                              ~ 1 | species_phylo,
                                                              ~ 1 | Authors,
                                                              ~ 1 | EffectID),
                                                method = "REML",
                                                R = list(species_phylo = phylo_cor.new),
                                                test = "t",
                                                data = metadata)

summary(small_study_effects.phylo.model.r.VCV,digits=3)

# figure_small_study_effects.phylo.model.r.VCV <- orchaRd::bubble_plot(small_study_effects.phylo.model.r.VCV, 
#                                                                      mod = "sqrt_inv_esz", 
#                                                                      group = "Authors",
#                                                                      g = T,
#                                                                      ylab = "Effect size (r & rbis)",
#                                                                      xlab = "squared root of 1/effective N",
#                                                                      legend.pos = "bottom.right")
# 
# figure_small_study_effects.phylo.model.r.VCV

# The amount of heterogeneity explained is:
round(r2_ml(small_study_effects.phylo.model.r.VCV)*100, 2)[1]


################################################################################
# testing for differences between effect size origin

effect.size.origin.phylo.model.r.VCV <- rma.mv(yi = yi,
                                               V = VCV_vi,
                                               mods = ~ 1 + Stat.Test,
                                               random = list(~ 1 | animal,
                                                             ~ 1 | species_phylo,
                                                             ~ 1 | Authors,
                                                             ~ 1 | EffectID),
                                               method = "REML",
                                               R = list(species_phylo = phylo_cor.new),
                                               test = "t",
                                               data = metadata)

summary(effect.size.origin.phylo.model.r.VCV,digits=3)

# removing intercept to see each effect size separately (but see Figure 1D)
fig_effect.size.origin.phylo.model.r.VCV <- orchaRd::orchard_plot(effect.size.origin.phylo.model.r.VCV, 
                                                                  mod = "Stat.Test", 
                                                                  group = "Authors", 
                                                                  xlab = "Effect size",
                                                                  trunk.size = 2,
                                                                  branch.size = 3,
                                                                  twig.size = 1)

fig_effect.size.origin.phylo.model.r.VCV # Figure 1D

# The amount of heterogeneity explained is: ~7%, still decent, but already less
# concerning
round(r2_ml(effect.size.origin.phylo.model.r.VCV)*100, 1)[1]


# arranging these two plots to create half of Figure 1, i.e., panels B and D
# the remaining of this figure was generated in script 005
grid.arrange(
  arrangeGrob(
    figure_phylo.model.r.VCV +
      theme(axis.title.x = element_blank(),
            axis.text.x  = element_text(size = 15),
            axis.text.y  = element_text(size = 15)) +
      annotate(
        geom = "text",
        x = 1.5, y = -0.75,
        label = paste0(
          "italic(I)^{2} == ",
          round(I2_phylo.model.r.VCV[[1]], 1),
          " *\"%\""
        ),
        parse = TRUE, size = 5.5
      ),
    top = textGrob("B)", x = unit(0, "npc"),
                   y = unit(1, "npc"),
                   just = c("left", "top"),
                   gp = gpar(fontsize = 14, fontface = "bold"))
  ),
  arrangeGrob(
    fig_effect.size.origin.phylo.model.r.VCV +
      theme(axis.title.x = element_text(size = 18, face = "bold"),
            axis.text.x  = element_text(size = 15),
            axis.text.y  = element_text(size = 15)) +
      annotate(
        geom = "text",
        x = 5.25, y = -0.75,
        label = paste0(
          "italic(R)[marginal]^{2} == ",
          round(r2_ml(effect.size.origin.phylo.model.r.VCV)*100, 1)[1],
          " *\"%\""
        ),
        parse = TRUE, size = 5.5
      ),
    top = textGrob("D)", x = unit(0, "npc"),
                   y = unit(1, "npc"),
                   just = c("left", "top"),
                   gp = gpar(fontsize = 14, fontface = "bold"))
  ),
  ncol = 1
)

